blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('cms.urls')),
    url(r'^posts/', include('cms.urls', namespace='posts')),
    url(r'^categories/', include('cms.urls', namespace='categories')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<post_id>[0-9]+)/single/$', views.single_post, name='single_post'),
    url(r'^(?P<category_id>[0-9]+)/posts/$', views.post_by_category, name='post_by_category'),
    url(r'^search', views.post_query, name='post_query'),
]

cms/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField

# Create category model.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=50)
    # description = models.TextField(max_length=250)
    description = RichTextField(config_name='awesome_ckeditor')

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

# Create tag model.
class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=50)
    description = RichTextField(config_name='awesome_ckeditor')

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

# Create post model.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    categories = models.ManyToManyField(Category, blank=True, null=True, through='CategoryToPost')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    status = models.BooleanField()
    featured_photo = models.ImageField(upload_to = "featured_photos", null=True, blank=True)
    description = RichTextField(config_name='awesome_ckeditor')
    pub_date = models.DateTimeField()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

class CategoryToPost(models.Model):
    post = models.ForeignKey(Post)
    category = models.ForeignKey(Category)

cms/views.py
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.db.models import Q
from cms.models import Post, Category, CategoryToPost

# Index view
def index(request):
    return HttpResponse("Hi")

# home view
def home(request):
    post_list = Post.objects.filter(status=True).order_by('-pub_date')
    paginator = Paginator(post_list, 5) # Show 25 contacts per page
    page = request.GET.get('page')

    try:
        blog_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blog_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blog_posts = paginator.page(paginator.num_pages)

    categories = Category.objects.all()
    template = loader.get_template('frontend/home.html')
    context = {
        'blog_posts': blog_posts,
        'categories': categories,
    }

    return HttpResponse(template.render(context, request))

# Get the single post details
def single_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    categories = Category.objects.all()
    template = loader.get_template('frontend/single.html')
    context = {
        'post': post,
        'categories': categories,
    }
    return HttpResponse(template.render(context, request))

# Get the post by category
def post_by_category(request, category_id):
    post_categories = CategoryToPost.objects.filter(category_id=category_id)

    post_ids = []
    for post_category in post_categories:
        post_ids.append(post_category.post_id)

    blog_posts = Post.objects.filter(Q(pk__in=post_ids) & Q(status=True))
    categories = Category.objects.all()
    template = loader.get_template('frontend/home.html')

    context = {
        'blog_posts': blog_posts,
        'categories': categories,
    }

    return HttpResponse(template.render(context, request))

# Get the post by search
def post_query(request):
    query_string = request.GET.get('q')
    blog_posts = Post.objects.filter(Q(status=True) & Q(title__contains=query_string) | Q(description__contains=query_string))
    categories = Category.objects.all()
    template = loader.get_template('frontend/home.html')

    context = {
        'blog_posts': blog_posts,
        'categories': categories,
        'query_string' : query_string
    }

    return HttpResponse(template.render(context, request))

cms/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Blog</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ STATIC_URL }}bootstrap/css/blog-post.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Porimol Chandro</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="http://porimolchandro.com/">About</a>
                        </li>
                        <li>
                            <a href="http://porimolchandro.com/#portfolio">Services</a>
                        </li>
                        <li>
                            <a href="http://porimolchandro.com/#contact">Contact</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">

            <div class="row">

                <!-- Blog Post Content Column -->
                <div class="col-lg-8">

                    {% block content %}

                    {% endblock %}

                    <!-- Blog Comments -->
                    <!-- Comments Form -->
                    <div class="well">
                        <h4>Leave a Comment:</h4>

                        <div id="disqus_thread"></div>
                        <script>
                            /**
                             *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                             *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
                             */
                            /*
                            var disqus_config = function () {
                                this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                                this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                            };
                            */
                            (function() {  // DON'T EDIT BELOW THIS LINE
                                var d = document, s = d.createElement('script');

                                s.src = '//porimolchandro.disqus.com/embed.js';

                                s.setAttribute('data-timestamp', +new Date());
                                (d.head || d.body).appendChild(s);
                            })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
                    </div>
                </div>

                <!-- Blog Sidebar Widgets Column -->
                <div class="col-md-4">

                    <!-- Blog Search Well -->
                    <div class="well">
                        <h4>Blog Post Search</h4>
                        <div class="input-group">
                            <form method="get" action="{% url 'posts:post_query' %}">
                                <input type="text" name="q" value="{{ query_string }}" class="form-control" required>
                                <span class="input-group-btn">
                                    <button class="btn btn-info" type="submit">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </form>
                        </div>
                        <!-- /.input-group -->
                    </div>

                    <!-- Blog Categories Well -->
                    <div class="well">
                        <h4>Blog Categories</h4>
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="list-unstyled">
                                    {% if categories %}
                                        {% for category in categories %}
                                           <li><a href="{% url 'categories:post_by_category' category.id %}">{{ category.name }}</a></li>
                                        {% endfor %}
                                    {% else %}
                                        <p>Categories are not available.</p>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <!-- /.row -->
                    </div>
                </div>
            </div>
            <!-- /.row -->

            <hr>

            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Porimol Chandro 2016</p>
                    </div>
                </div>
                <!-- /.row -->
            </footer>

        </div>
        <!-- /.container -->

        <!-- jQuery -->
        <script src="{{ STATIC_URL }}bootstrap/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

cms/templates/frontend/home.html
{% extends "frontend/base.html" %}
    {% block content %}
        <!-- Blog Post -->
        {% if blog_posts %}
            {% for post in blog_posts %}
                <!-- Title -->
                <h1><a href="{% url 'posts:single_post' post.id %}">{{ post.title }}</a></h1>

                <!-- Author -->
                <p class="lead">
                    Category :
                    {% for category in post.categories.all %}
                    <a href="{% url 'categories:post_by_category' category.id %}">{{ category.name }}</a>
                    {% endfor %}
                </p>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.pub_date }}</p>
                <hr>

                <!-- Preview Image -->
                <img src="{{ MEDIA_URL }}{{ post.featured_photo }}" style="width:100%; height: 230px;">
                <hr>

                <!-- Post Content -->
                <p class="lead">{{ post.description|safe|truncatechars:180 }}</p>
                <a href="{% url 'posts:single_post' post.id %}" class="btn btn-default">Read more >></a>
                <hr>

            {% endfor %}

            <div class="row" style="padding: 0px 0px 10px;">
                <div class="col-md-5">
                    {% if blog_posts.has_previous %}
                        <a href="?page={{ blog_posts.previous_page_number }}" class="btn btn-info pull-left">&lt;&lt; Previous</a>
                    {% endif %}
                </div>

                <div class="col-md-2">
                    <span class="current">
                        Page {{ blog_posts.number }} of {{ blog_posts.paginator.num_pages }}.
                    </span>
                </div>

                <div class="col-md-5">
                    {% if blog_posts.has_next %}
                        <a href="?page={{ blog_posts.next_page_number }}" class="btn btn-info pull-right">Next &gt;&gt;</a>
                    {% endif %}
                </div>
            </div>

        {% else %}
            <div class="jumbotron" style="text-align:center;">
                <h1>Nothing Found!</h1>
                <p>Sorry, but nothing matched your search terms. Please try again with some different keywords.</p>
                <p>
                    <a role="button" href="/" class="btn btn-lg btn-primary">Go Back To Home »</a>
                </p>
            </div>
        {% endif %}
    {% endblock %}

cms/templates/frontend/single.html
{% extends "frontend/base.html" %}
    {% block content %}
        <!-- Blog Post -->
        {% if post %}
            <!-- Title -->
            <h1><a href="{% url 'posts:single_post' post.id %}">{{ post.title }}</a></h1>

            <!-- Author -->
            <p class="lead">
                Category :
                {% for category in post.categories.all %}
                    <a href="{% url 'categories:post_by_category' category.id %}">{{ category.name }}</a>
                {% endfor %}
            </p>

            <!-- Date/Time -->
            <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.pub_date }}</p>

            <hr>

            <!-- Preview Image -->
            {% if post.featured_photo %}
                <img src="{{MEDIA_URL}}{{ post.featured_photo }}" style="width:100%; height: 230px;">
            {% else %}
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
            {% endif %}
            <hr>

            <!-- Post Content -->
            <p class="lead">{{ post.description|safe }}</p>
            <hr>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% endblock %}

frontend/templates/frontend/home.html
{% extends "frontend/base.html" %}
    {% block content %}
        <!-- Blog Post -->
        {% if blog_posts %}
            {% for post in blog_posts %}
                <!-- Title -->
                <h1><a href="/posts/{{ post.id }}/single/">{{ post.title }}</a></h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Porimol</a>
                </p>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.pub_date }}</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <img class="img-responsive" src="{{ post.featured_photo }}" alt="">
                <hr>

                <!-- Post Content -->
                <p class="lead">{{ post.description }}</p>
                <hr>

            {% endfor %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% endblock %}